function tf = is_valid_mrdmd_mode(list_modes, list_w, lev, bin, mode_idx)
%IS_VALID_MRDMD_MODE Check whether [level, bin, mode] exists before plotting.

tf = lev <= size(list_modes, 1) && ...
     bin <= size(list_modes, 2) && ...
     ~isempty(list_modes{lev, bin}) && ...
     mode_idx <= size(list_modes{lev, bin}, 2) && ...
     mode_idx <= length(list_w{lev, bin});

end

